---
- hosts: all
  become: true
  vars:
    cni_plugin: calico
    calico_manifest_uri: https://docs.projectcalico.org/v3.8/manifests/calico.yaml
    flannel_manifest_uri: "https://raw.githubusercontent.com/coreos/flannel/\
        62e44c867a2846fefb68bd5f178daf4da3095ccb/Documentation/kube-flannel.yml"
    canal_manifest_uri: https://docs.projectcalico.org/v3.8/manifests/canal.yaml
    k8s_network_config:
      calico:
        pod_network_cidr: '192.168.0.0/16'
        manifest_uri: "{{ calico_manifest_uri }}"
      flannel:
        pod_network_cidr: '10.244.0.0/16'
        manifest_uri: "{{ flannel_manifest_uri }}"
      canal:
        pod_network_cidr: '10.244.0.0/16'
        manifest_uri: "{{ canal_manifest_uri }}"
    docker_version: latest
    k8s_version: latest
  tasks:
  - import_tasks: tasks/install_docker.yml
  - import_tasks: tasks/disable_swap.yml
  - import_tasks: tasks/install_k8s.yml

  - name: Initialize the Kubernetes cluster using kubeadm
    command: >-
      kubeadm init --apiserver-advertise-address="192.168.50.10"
      --apiserver-cert-extra-sans="192.168.50.10" --node-name k8s-master
      --pod-network-cidr={{ pod_network_cidr }}
    args:
      creates: /etc/kubernetes/admin.conf
    vars:
      pod_network_cidr: "{{ k8s_network_config[cni_plugin]['pod_network_cidr'] }}"

  - name: Setup kubeconfig for vagrant user
    command: "{{ item }}"
    with_items:
    - mkdir -p /home/vagrant/.kube
    - cp -i /etc/kubernetes/admin.conf /home/vagrant/.kube/config
    - chown vagrant:vagrant /home/vagrant/.kube/config

  - name: Install {{ cni_plugin }} pod network
    become: false
    command: >
      kubectl apply -f {{ manifest_uri }}
    vars:
      manifest_uri: "{{ k8s_network_config[cni_plugin]['manifest_uri'] }}"

  - name: Generate join command
    command: kubeadm token create --print-join-command
    register: join_command

  - name: Copy join command to local file
    local_action: copy content="{{ join_command.stdout_lines[0] }}" dest="/vagrant/join-command"

  handlers:
  - import_tasks: handlers/main.yml
